In [14]:
# 1) 학습데이터(Training data) 준비
import numpy as np

x_data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]).reshape(10,1)
t_data = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1]).reshape(10,1)

# 2) 임의의 직선 z = Wx + b 정의(임의의 값으로 가중치 W, 바이어스 b 초기화)
W = np.random.rand(1,1)
b = np.random.rand(1)
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

# 3) 손실함수 E(W, b) 정의
def sigmoid(x):
    return 1 / (1+np.exp(-x))

def loss_func(x, t):
    delta = 1e-7 # log 무한대 발산 방지
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    # cross-entropy
    return -np.sum(t * np.log(y + delta) + (1-t) * np.log((1-y)+delta))


# 4) 수치미분 numerical_derivative 및 utility 함수 정의
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

def error_val(x, t):
    delta = 1e-07 # log 무한대 발산 방지
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    # cross-entropy
    return -np.sum( t*np.log(y + delta) + (1-t)*np.log((1-y) + delta))

def predict(x):
    z =  np.dot(x ,W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1 # True
    else:
        result = 0 # False
        
    return y, result

# 5) 학습율 초기화 및 손실함수가 최소가 될 때까지 W, b 업데이트

learning_rate = 1e-2 # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f = lambda x : loss_func(x_data, t_data) # f(x) = loss_func(x_data, t_data)
print("initial error value = ", error_val(x_data, t_data), "initial W = ", W, "\n", ", b = ", b)

for step in range(10001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, "b = ", b)

W =  [[0.5044036]] , W.shape =  (1, 1) , b =  [0.19215832] , b.shape =  (1,)
initial error value =  22.767046168345768 initial W =  [[0.5044036]] 
 , b =  [0.19215832]
step =  0 error value =  7.868623214426062 W =  [[0.09737796]] b =  [0.15563017]
step =  400 error value =  2.9187188130572124 W =  [[0.43231746]] b =  [-4.24988129]
step =  800 error value =  1.7620961761434477 W =  [[0.45888986]] b =  [-5.71476244]
step =  1200 error value =  1.505424175370773 W =  [[0.53491682]] b =  [-6.72691807]
step =  1600 error value =  1.3439924700917047 W =  [[0.59543001]] b =  [-7.53036559]
step =  2000 error value =  1.22974268862108 W =  [[0.64646092]] b =  [-8.20645335]
step =  2400 error value =  1.1429531209331045 W =  [[0.69101859]] b =  [-8.79574443]
step =  2800 error value =  1.073840246564541 W =  [[0.73083722]] b =  [-9.32159572]
step =  3200 error value =  1.0169216151138765 W =  [[0.7670148]] b =  [-9.79877915]
step =  3600 error value =  0.9688511316323558 W =  [[0.80029411]] b =

In [16]:
(real_val, logical_val) = predict(3) # 공부시간 3시간 미래값 예측

print(real_val, logical_val) # 0.1 보다 작은 real값


[[1.10906237e-05]] 0


(array([[1.10906237e-05]]), 0)

In [17]:
(real_val, logical_val) = predict(17) # 공부시간 17시간 미래값 예측

print(real_val, logical_val) # real_val = 공부시간 17시간이면 99.1% 확률로 합격할 확률

[[0.99132011]] 1


In [19]:
# multi-variable logistic regression(classification) - example

# 1) 학습데이터(Training Data) 준비

import numpy as np

x_data = np.array([ [2,4], [4,11], [6,6], [8,5], [10,7], [12,16], [14,8], [16,3], [18,7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9,1)

# 2) 임의의 직선 z = W1x1 + W2x2 + b 정의 (가중치 W, 바이어스 b 초기화)

W = np.random.rand(2,1) # 2X1 행렬
b = np.random.rand(1)
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def loss_func(x, t):
    delta = 1e-7 # log 무한대 발산 방지
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    # cross-entropy
    return -np.sum( t*np.log(y + delta) + (1-t) * np.log((1-y) + delta ))

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

def error_val(x, t):
    delta = 1e-7 # log 무한대 발산 방지
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    # cross-entropy
    return -np.sum( t*np.log(y + delta) + (1-t)*np.log((1-y) + delta))

def predict(x):
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1 # True
    else:
        result = 0 # False
        
    return y, result

# 5) 학습율 초기화 및 손실함수가 최소가 될 때까지 W, b 업데이트

learning_rate  = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("initial error value = ", error_val(x_data, t_data), "initial W = ", W, "\n", ", b = ", b)

for step in range(80001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ", b)

W =  [[0.36151567]
 [0.62842551]] , W.shape =  (2, 1) , b =  [0.8247337] , b.shape =  (1,)
initial error value =  26.886908645055026 initial W =  [[0.36151567]
 [0.62842551]] 
 , b =  [0.8247337]
step =  0 error value =  16.127083117334063 W =  [[0.1621146 ]
 [0.36937122]] , b =  [0.7860258]
step =  400 error value =  2.3338595225925953 W =  [[ 0.41286012]
 [-0.09160248]] , b =  [-2.50859233]
step =  800 error value =  1.6145077332145628 W =  [[ 0.53091894]
 [-0.02878952]] , b =  [-4.19145555]
step =  1200 error value =  1.2923648247837485 W =  [[0.61920434]
 [0.00742894]] , b =  [-5.32250539]
step =  1600 error value =  1.1060128351971474 W =  [[0.69025659]
 [0.03302471]] , b =  [-6.18374284]
step =  2000 error value =  0.9821541537732866 W =  [[0.75003137]
 [0.05330718]] , b =  [-6.88610878]
step =  2400 error value =  0.8923723675983923 W =  [[0.80179233]
 [0.07060595]] , b =  [-7.48414523]
step =  2800 error value =  0.8233440191039261 W =  [[0.8475234 ]
 [0.08611751]] , b =  [-8.0

step =  32400 error value =  0.16656237392568482 W =  [[1.79632336]
 [0.7135181 ]] , b =  [-20.3671582]
step =  32800 error value =  0.16481161132494748 W =  [[1.80252153]
 [0.71813245]] , b =  [-20.45054588]
step =  33200 error value =  0.16309678991303642 W =  [[1.80865798]
 [0.72269567]] , b =  [-20.53307266]
step =  33600 error value =  0.16141682300627716 W =  [[1.81473393]
 [0.72720887]] , b =  [-20.61475591]
step =  34000 error value =  0.15977066709982765 W =  [[1.82075053]
 [0.73167313]] , b =  [-20.69561251]
step =  34400 error value =  0.15815731974687477 W =  [[1.82670892]
 [0.73608946]] , b =  [-20.77565881]
step =  34800 error value =  0.15657581756175648 W =  [[1.83261019]
 [0.74045887]] , b =  [-20.85491069]
step =  35200 error value =  0.15502523433879895 W =  [[1.83845542]
 [0.74478234]] , b =  [-20.93338358]
step =  35600 error value =  0.15350467927892614 W =  [[1.84424563]
 [0.74906081]] , b =  [-21.01109247]
step =  36000 error value =  0.15201329531688212 W =  [[

step =  64800 error value =  0.08921480384853461 W =  [[2.16444378]
 [0.98019206]] , b =  [-25.27618548]
step =  65200 error value =  0.08870366191541235 W =  [[2.16784592]
 [0.98260112]] , b =  [-25.32122845]
step =  65600 error value =  0.08819830263469666 W =  [[2.17122911]
 [0.98499598]] , b =  [-25.36601581]
step =  66000 error value =  0.08769862892555093 W =  [[2.17459354]
 [0.98737679]] , b =  [-25.41055042]
step =  66400 error value =  0.0872045458597531 W =  [[2.17793943]
 [0.98974373]] , b =  [-25.45483509]
step =  66800 error value =  0.08671596060255982 W =  [[2.18126697]
 [0.99209693]] , b =  [-25.4988726]
step =  67200 error value =  0.0862327823554727 W =  [[2.18457636]
 [0.99443658]] , b =  [-25.54266567]
step =  67600 error value =  0.08575492230089303 W =  [[2.1878678 ]
 [0.99676281]] , b =  [-25.58621697]
step =  68000 error value =  0.08528229354853274 W =  [[2.19114148]
 [0.99907578]] , b =  [-25.62952915]
step =  68400 error value =  0.08481481108359429 W =  [[2.

In [21]:
test_data = np.array([3, 17]) # (예습, 복습) = (3, 17) => Fail (0)
predict(test_data)

(array([0.12863303]), 0)

In [24]:
test_data = np.array([5, 8])
predict(test_data)

(array([0.00099094]), 0)

In [23]:
test_data = np.array([7, 21])
predict(test_data)

(array([0.99998952]), 1)

In [22]:
test_data = np.array([12, 0])
predict(test_data)

(array([0.63506371]), 1)

미래값을 예측해보면, 복습보다는 예습시간이 합격(Pass)에 미치는 영향이 크다는 것을 알 수 있음

즉, 예습시간에 대한 가중치 W1 = 2.28, 복습시간에 대한 가중치 W2 = 1.06 에서 보듯이 예습시간이 복습시간에 비해 최종결과에 미치는 영향이 2배 이상임.